### PR TITLE
Update small QR-DQN docs typo

### PR DESCRIPTION
**Pull request by minhlong94**
Fix checkmark in QR-DQN docs column typo

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/CONTRIBUTING.md) guide (**required**)
- [x] The functionality/performance matches that of the source (**required** for new training algorithms or training-related features).
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have included an example of using the feature (*required for new features*).
- [ ] I have included baseline results (**required** for new training algorithms or training-related features).
- [x] I have updated the documentation accordingly.
- [x] I have updated the changelog accordingly (**required**).
- [x] I have reformatted the code using `make format` (**required**)
- [x] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [x] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by Miffyli** [comment]
Thanks for the PR! Remember to also update changelog (see checklist) :)

**Comment by araffin** [comment]
Hello,
thanks for the PR =) (indeed there was a small inconsitency there)
Could you please add an entry in the changelog too?

**Comment by minhlong94** [comment]
Hello,

First time contributing though :D how should I update the changelog? Add a section like this:
```
2021-06-23: update QR-DQN docs checkmark typo
```
Between the `Changelog` title and `Release 1.1.0a11`?

**Comment by Miffyli** [comment]
Add a bullet-point under "Documentation:" describing the update and add your github nick to the list of nicknames at the end of the list [here](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/docs/misc/changelog.rst).

**Comment by minhlong94** [comment]
I added the change in `changelog`

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
