### PR TITLE
Deprecation of shared layers in `mlp_extractor`

### PR DESCRIPTION
**Pull request by AlexPasqua**
## Description

Equivalent to DLR-RM/stable-baselines3#1252

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/blob/master/CONTRIBUTING.md) guide (**required**)
- [ ] The functionality/performance matches that of the source (**required** for new training algorithms or training-related features).
- [ ] I have updated the tests accordingly (*required for a bug fix or a new feature*).
- [ ] I have included an example of using the feature (*required for new features*).
- [ ] I have included baseline results (**required** for new training algorithms or training-related features).
- [ ] I have updated the documentation accordingly.
- [x] I have updated the changelog accordingly (**required**).
- [ ] I have reformatted the code using `make format` (**required**)
- [ ] I have checked the codestyle using `make check-codestyle` and `make lint` (**required**)
- [ ] I have ensured `make pytest` and `make type` both pass. (**required**)

Note: we are using a maximum length of 127 characters per line

### CODE REVIEW

**Comment by AlexPasqua** [comment]
@araffin I was about to update the tests, but if you're doing it, then I stop, so we don't push commits the both of us 😅

**Comment by araffin** [comment]
> I was about to update the tests

sorry, I'm done now ;). Please push your changes in case I missed something.

**Comment by AlexPasqua** [comment]
> > I was about to update the tests
> 
> sorry, I'm done now ;). Please push your changes in case I missed something.

All tests passed, so it looks good as it is 👍 

> EDIT: I prepared the RL Zoo PR

Alright 👍

**Review by araffin — APPROVED** [review]
LGTM, thanks =)

**Pull request merged**
